server:
  port: 7777
spring:
  main:
#    //循环依赖
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/hb_sql
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#    swagger 配置
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
#  用来把数据库对象的字段变为下划线
#  jackson:
#    property-naming-strategy: SNAKE_CASE

#  configuration:
#    map-underscore-to-camel-case: true
  servlet:
    multipart:
      # maxFileSize 单个数据大小
      # maxRequestSize 是总数据大小
      max-file-size: 20MB
      max-request-size: 100MB
  profiles:
    active: dev
#      --spring.profiles.active=prod
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

#logging:
##  file:
##    name: server.log
#  logback:
#    rollingpolicy:
#      max-file-size: 5MB
#  file:
#    path: log


#  pattern:
#    console: "%d %-5level %logger : %msg%n"
#    file: "%d %-5level [%thread] %logger : %msg%n"

#Windows下的路径配置
ImagesFilePath: E:\\sch-work-space\\projects\\hbkj\\hboa\\admin\\src\\main\\resources\\images\\
ExcelFilePath: E:\\sch-work-space\\projects\\hbkj\\hboa\\admin\\src\\main\\resources\\excel\\
#linux下的路径配置
#ImagesFilePath: /usr/local/images/